INSERT INTO "product_types" VALUES(1,'Bebidas Quentes','active');
INSERT INTO "product_types" VALUES(2,'Bebidas Frias','active');
INSERT INTO "product_types" VALUES(3,'Lanches','active');
INSERT INTO "product_types" VALUES(4,'Sobremesas','active');
INSERT INTO "product_types" VALUES(5,'Pratos Principais','active');
INSERT INTO "product_types" VALUES(6,'Saladas','active');
INSERT INTO "product_types" VALUES(7,'Sanduíches','active');
INSERT INTO "product_types" VALUES(8,'Café da Manhã','active');

INSERT INTO "products" VALUES(1,'Café Expresso',1,800,'active');
INSERT INTO "products" VALUES(2,'Cappuccino',1,1200,'active');
INSERT INTO "products" VALUES(3,'Latte',1,1400,'active');
INSERT INTO "products" VALUES(4,'Café Americano',1,1000,'active');
INSERT INTO "products" VALUES(5,'Chocolate Quente',1,1300,'active');
INSERT INTO "products" VALUES(6,'Mocha',1,1500,'active');
INSERT INTO "products" VALUES(7,'Chai Latte',1,1400,'active');
INSERT INTO "products" VALUES(8,'Matcha Latte',1,1600,'active');
INSERT INTO "products" VALUES(9,'Flat White',1,1300,'active');
INSERT INTO "products" VALUES(10,'Chá de Ervas',1,900,'active');
INSERT INTO "products" VALUES(11,'Café Gelado',2,1200,'active');
INSERT INTO "products" VALUES(12,'Latte Gelado',2,1400,'active');
INSERT INTO "products" VALUES(13,'Mocha Gelado',2,1500,'active');
INSERT INTO "products" VALUES(14,'Chá Gelado de Limão',2,1000,'active');
INSERT INTO "products" VALUES(15,'Chá Gelado de Pêssego',2,1000,'active');
INSERT INTO "products" VALUES(16,'Suco Natural de Laranja',2,1100,'active');
INSERT INTO "products" VALUES(17,'Suco Natural de Limão',2,1000,'active');
INSERT INTO "products" VALUES(18,'Água com Gás',2,600,'active');
INSERT INTO "products" VALUES(19,'Coca-Cola',2,800,'active');
INSERT INTO "products" VALUES(20,'Sprite',2,800,'active');
INSERT INTO "products" VALUES(21,'Vitamina de Morango e Banana',2,1600,'active');
INSERT INTO "products" VALUES(22,'Vitamina de Manga e Abacaxi',2,1600,'active');
INSERT INTO "products" VALUES(23,'Milkshake de Chocolate',2,1500,'active');
INSERT INTO "products" VALUES(24,'Milkshake de Baunilha',2,1500,'active');
INSERT INTO "products" VALUES(25,'Batata Frita',3,1000,'active');
INSERT INTO "products" VALUES(26,'Batata Frita com Queijo',3,1200,'active');
INSERT INTO "products" VALUES(27,'Anéis de Cebola',3,1100,'active');
INSERT INTO "products" VALUES(28,'Pão de Alho',3,900,'active');
INSERT INTO "products" VALUES(29,'Palitos de Mussarela',3,1300,'active');
INSERT INTO "products" VALUES(30,'Nachos',3,1400,'active');
INSERT INTO "products" VALUES(31,'Pipoca',3,700,'active');
INSERT INTO "products" VALUES(32,'Pretzel',3,800,'active');
INSERT INTO "products" VALUES(33,'Rolinhos Primavera',3,1200,'active');
INSERT INTO "products" VALUES(34,'Mini Tacos',3,1300,'active');
INSERT INTO "products" VALUES(35,'Bolo de Chocolate',4,1500,'active');
INSERT INTO "products" VALUES(36,'Cheesecake',4,1500,'active');
INSERT INTO "products" VALUES(37,'Brownie',4,1000,'active');
INSERT INTO "products" VALUES(38,'Sorvete de Baunilha',4,900,'active');
INSERT INTO "products" VALUES(39,'Sorvete de Chocolate',4,900,'active');
INSERT INTO "products" VALUES(40,'Waffle',4,1200,'active');
INSERT INTO "products" VALUES(41,'Panquecas',4,1300,'active');
INSERT INTO "products" VALUES(42,'Salada de Frutas',4,1100,'active');
INSERT INTO "products" VALUES(43,'Tiramisu',4,1400,'active');
INSERT INTO "products" VALUES(44,'Rosquinha',4,800,'active');
INSERT INTO "products" VALUES(45,'Frango Grelhado',5,2500,'active');
INSERT INTO "products" VALUES(46,'Bife com Batata Frita',5,3500,'active');
INSERT INTO "products" VALUES(47,'Peixe com Batata Frita',5,2800,'active');
INSERT INTO "products" VALUES(48,'Espaguete à Bolonhesa',5,2400,'active');
INSERT INTO "products" VALUES(49,'Refogado de Legumes',5,2200,'active');
INSERT INTO "products" VALUES(50,'Hambúrguer de Carne',5,2000,'active');
INSERT INTO "products" VALUES(51,'Hambúrguer de Frango',5,2000,'active');
INSERT INTO "products" VALUES(52,'Hambúrguer Vegano',5,2200,'active');
INSERT INTO "products" VALUES(53,'Costela ao Barbecue',5,3800,'active');
INSERT INTO "products" VALUES(54,'Costeletas de Cordeiro',5,4000,'active');
INSERT INTO "products" VALUES(55,'Salada Caesar',6,1800,'active');
INSERT INTO "products" VALUES(56,'Salada Grega',6,1700,'active');
INSERT INTO "products" VALUES(57,'Salada Cobb',6,1900,'active');
INSERT INTO "products" VALUES(58,'Salada Verde',6,1500,'active');
INSERT INTO "products" VALUES(59,'Salada de Quinoa',6,2000,'active');
INSERT INTO "products" VALUES(60,'Salada de Frango',6,1900,'active');
INSERT INTO "products" VALUES(61,'Sanduíche Club',7,1800,'active');
INSERT INTO "products" VALUES(62,'Sanduíche BLT',7,1700,'active');
INSERT INTO "products" VALUES(63,'Sanduíche de Presunto e Queijo',7,1500,'active');
INSERT INTO "products" VALUES(64,'Sanduíche de Peru',7,1600,'active');
INSERT INTO "products" VALUES(65,'Sanduíche Vegetariano',7,1500,'active');
INSERT INTO "products" VALUES(66,'Queijo Quente',7,1400,'active');
INSERT INTO "products" VALUES(67,'Sanduíche de Atum',7,1600,'active');
INSERT INTO "products" VALUES(68,'Wrap de Frango',7,1700,'active');
INSERT INTO "products" VALUES(69,'Wrap de Falafel',7,1600,'active');
INSERT INTO "products" VALUES(70,'Wrap de Carne',7,1800,'active');
INSERT INTO "products" VALUES(71,'Ovos Mexidos',8,1200,'active');
INSERT INTO "products" VALUES(72,'Omelete',8,1400,'active');
INSERT INTO "products" VALUES(73,'Torrada com Abacate',8,1500,'active');
INSERT INTO "products" VALUES(74,'Mingau',8,1100,'active');
INSERT INTO "products" VALUES(75,'Rabanada',8,1400,'active');
INSERT INTO "products" VALUES(76,'Bagel com Cream Cheese',8,1000,'active');
INSERT INTO "products" VALUES(77,'Croissant',8,900,'active');
INSERT INTO "products" VALUES(78,'Burrito de Café da Manhã',8,1600,'active');
INSERT INTO "products" VALUES(79,'Muffin de Ovo',8,1200,'active');
INSERT INTO "products" VALUES(80,'Iogurte com Granola',8,1300,'active');
INSERT INTO "products" VALUES(81,'Café Expresso Duplo',1,1000,'active');
INSERT INTO "products" VALUES(82,'Latte de Caramelo',1,1500,'active');
INSERT INTO "products" VALUES(83,'Macchiato Gelado de Caramelo',2,1600,'active');
INSERT INTO "products" VALUES(84,'Energético',2,1200,'active');
INSERT INTO "products" VALUES(85,'Batata Doce Frita',3,1200,'active');
INSERT INTO "products" VALUES(86,'Sorvete de Morango',4,900,'active');
INSERT INTO "products" VALUES(87,'Salmão Grelhado',5,3400,'active');
INSERT INTO "products" VALUES(88,'Macarrão com Camarão',5,3200,'active');
INSERT INTO "products" VALUES(89,'Salada de Macarrão Oriental',6,1800,'active');
INSERT INTO "products" VALUES(90,'Panini Italiano',7,1700,'active');
INSERT INTO "products" VALUES(91,'Sanduíche de Café da Manhã',8,1500,'active');
INSERT INTO "products" VALUES(92,'Água de Coco',2,900,'active');
INSERT INTO "products" VALUES(93,'Vitamina de Banana',2,1500,'active');
INSERT INTO "products" VALUES(94,'Jalapeños Recheados',3,1300,'active');
INSERT INTO "products" VALUES(95,'Cupcake',4,800,'active');
INSERT INTO "products" VALUES(96,'Tacos de Carne',5,2200,'active');
INSERT INTO "products" VALUES(97,'Pizza Vegetariana',5,2400,'active');
INSERT INTO "products" VALUES(98,'Macarrão Alfredo',5,2600,'active');
INSERT INTO "products" VALUES(99,'Salada de Abacate',6,1900,'active');
INSERT INTO "products" VALUES(100,'Bagel com Salmão Defumado',8,1700,'active');
